# Generated by Django 4.2.7 on 2026-01-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20, verbose_name='Bildirim Tipi')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Alıcı Telefon')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('sent', 'Gönderildi'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Durum')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment', verbose_name='Randevu')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
