# Generated by Django 4.2.7 on 2026-01-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(db_index=True, verbose_name='Randevu Tarihi')),
                ('appointment_time', models.TimeField(verbose_name='Randevu Saati')),
                ('procedure', models.CharField(blank=True, max_length=200, null=True, verbose_name='İşlem')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal'), ('no_show', 'Gelmedi')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='09:00', verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(default='18:00', verbose_name='Bitiş Saati')),
                ('slot_duration', models.IntegerField(default=15, verbose_name='Randevu Aralığı (dakika)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Randevu Ayarı',
                'verbose_name_plural': 'Randevu Ayarları',
            },
        ),
    ]
