# Generated by Django 4.2.7 on 2026-01-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='treatment_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='treatments.treatmenttype', verbose_name='Tedavi Türü'),
        ),
    ]
