# Generated by Django 4.2.7 on 2026-01-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=150, verbose_name='Soyad')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Telefon')),
                ('tc_identity_number', models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='TC Kimlik No')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='Son Ziyaret')),
            ],
            options={
                'verbose_name': 'Hasta',
                'verbose_name_plural': 'Hastalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAnamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Tıbbi Geçmiş')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Alerjiler')),
                ('medications', models.TextField(blank=True, null=True, verbose_name='Kullandığı İlaçlar')),
                ('chronic_diseases', models.TextField(blank=True, null=True, verbose_name='Kronik Hastalıklar')),
                ('past_surgeries', models.TextField(blank=True, null=True, verbose_name='Geçirdiği Ameliyatlar')),
                ('family_history', models.TextField(blank=True, null=True, verbose_name='Aile Öyküsü')),
                ('smoking', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sigara Kullanımı')),
                ('alcohol', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alkol Kullanımı')),
                ('pregnancy_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gebelik Durumu')),
                ('other_notes', models.TextField(blank=True, null=True, verbose_name='Diğer Notlar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Hasta Anamnezi',
                'verbose_name_plural': 'Hasta Anamnezleri',
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('file', models.FileField(upload_to='patient_documents/%Y/%m/%d/', verbose_name='Dosya')),
                ('file_type', models.CharField(max_length=50, verbose_name='Dosya Tipi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Hasta Dokümanı',
                'verbose_name_plural': 'Hasta Dokümanları',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
