# Generated by Django 4.2.7 on 2026-01-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='tc_identity_number',
            field=models.TextField(blank=True, help_text='Şifrelenmiş olarak saklanır', null=True, verbose_name='TC Kimlik No'),
        ),
    ]
