# Generated by Django 4.2.7 on 2026-01-14 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odontogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_teeth', models.JSONField(default=dict, verbose_name='Olgun Dişler')),
                ('primary_teeth', models.JSONField(default=dict, verbose_name='Süt Dişleri')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Odontogram',
                'verbose_name_plural': 'Odontogramlar',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(blank=True, help_text='FDI notasyonu (örn: 16, 21, 36)', max_length=10, null=True, verbose_name='Diş Numarası')),
                ('is_primary_tooth', models.BooleanField(default=False, verbose_name='Süt Dişi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('planned', 'Yapılacak'), ('completed', 'Tamamlanmış')], default='planned', max_length=20, verbose_name='Durum')),
                ('treatment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tedavi Tarihi')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Tedavi',
                'verbose_name_plural': 'Tedaviler',
                'ordering': ['-treatment_date'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tedavi Adı')),
                ('default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Varsayılan Fiyat')),
                ('color_code', models.CharField(default='#000000', max_length=7, verbose_name='Renk Kodu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Tedavi Türü',
                'verbose_name_plural': 'Tedavi Türleri',
                'ordering': ['name'],
            },
        ),
    ]
