# Generated by Django 4.2.7 on 2026-01-14 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to=settings.AUTH_USER_MODEL, verbose_name='Doktor'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient', verbose_name='Hasta'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='treatments.treatmenttype', verbose_name='Tedavi Türü'),
        ),
        migrations.AddField(
            model_name='odontogram',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontogram', to='patients.patient', verbose_name='Hasta'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['patient', '-treatment_date'], name='treatments__patient_09f8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['status'], name='treatments__status_3797c0_idx'),
        ),
    ]
